export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
export const CHANGE_SEARCHTAGFIELD = 'CHANGE_SEARCHTAGFIELD';

export const REQUEST_STUDENTS_PENDING = 'REQUEST_STUDENTS_PENDING';
export const REQUEST_STUDENTS_SUCCESS = 'REQUEST_STUDENTS_SUCCESS';
export const REQUEST_STUDENTS_FAILED = 'REQUEST_STUDENTS_FAILED';

export const UPDATE_STUDENTS_DATA = 'UPDATE_STUDENTS_DATA';
export const FILTERED_STUDENTS_DATA = 'FILTERED_STUDENTS_DATA';
